version: '3.4'

services:
  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: OrderApi/Dockerfile

  customerservice:
    image: ${DOCKER_REGISTRY-}customerservice
    build:
      context: .
      dockerfile: CustomerService/Dockerfile


  ticketapi:
    image: ${DOCKER_REGISTRY-}ticketapi
    build:
      context: .
      dockerfile: TicketApi/Dockerfile

  redis:
    image: redis
  cacheapi:
    image: ${DOCKER_REGISTRY-}cacheapi
    build:
      context: .
      dockerfile: CacheApi/Dockerfile

